// Editorial scale: 1-3 serious drawbacks, 4-6 mixed impressions,
// 7-9 small quirks with increasingly positive traits, 10 an endearing bonus.
// Each phrase belongs to one exact card value; ratings remain a party-game judgment.
internal sealed record HintCard(int Number, string Category, string Text);

internal static class HintCatalog
{
    internal static readonly HintCard[] Cards =
    [
        new(1, "hot", "usa lo que le contaste en confianza para humillarte delante de su próxima conquista."),
        new(1, "hot", "cree que coquetear le da permiso para ignorar todos tus límites."),
        new(2, "hot", "te invita a una cita solo para provocar celos a otra persona."),
        new(2, "hot", "reenvía tus mensajes románticos al grupo para que se rían de ti."),
        new(3, "hot", "te compara con su ex durante toda la cita y espera que lo tomes como un cumplido."),
        new(3, "hot", "presume de sus conquistas mientras tú intentas conocerle."),
        new(4, "hot", "solo coquetea contigo cuando se aburre y desaparece en cuanto propones un plan."),
        new(4, "hot", "convierte cada conversación en un monólogo sobre lo irresistible que es."),
        new(5, "hot", "tiene química contigo en persona, pero por chat parece estar respondiendo una encuesta."),
        new(5, "hot", "coquetea tan bien como se distrae: a mitad del cumplido ya está mirando el móvil."),
        new(6, "hot", "prepara una cita bonita, aunque termina contando la misma anécdota varias veces."),
        new(6, "hot", "te hace reír y te escucha, pero sus piropos parecen sacados de un calendario viejo."),
        new(7, "hot", "te trata con cariño, aunque ensaya sus frases de ligue y se le nota un poquito."),
        new(7, "hot", "recuerda lo que te gusta, pero necesita un rato para vencer los nervios de la cita."),
        new(8, "hot", "te pregunta antes de acercarse y luego se pone rojo por haberlo preguntado."),
        new(8, "hot", "te mira con tanta atención que se le enfría el café mientras te escucha."),
        new(9, "hot", "te hace sentir deseado y respetado; su único fallo es sonreír antes de terminar el piropo."),
        new(9, "hot", "convierte una cita sencilla en un recuerdo precioso y guarda hasta el ticket de recuerdo."),
        new(10, "hot", "además de la química, te escucha, respeta tu ritmo y te hace sentir completamente a gusto."),
        new(10, "hot", "su mejor forma de seducirte es cuidarte sin dejar de preguntarte qué te apetece."),

        new(1, "pareja", "quiere decidir con quién hablas y te exige pruebas de todo lo que haces."),
        new(1, "pareja", "te hace sentir culpable cada vez que dices que algo te duele."),
        new(2, "pareja", "rompe sus promesas importantes y luego insiste en que tú te lo inventaste."),
        new(2, "pareja", "solo celebra tus logros cuando puede atribuirse el mérito."),
        new(3, "pareja", "cancela los planes que te importan, pero se enfada si no vas a los suyos."),
        new(3, "pareja", "espera que resuelvas todos sus problemas y nunca tiene tiempo para los tuyos."),
        new(4, "pareja", "elige siempre el plan sin preguntarte y negociar la cena parece una reunión eterna."),
        new(4, "pareja", "necesita que le recuerdes cada tarea compartida como si llevaras su agenda."),
        new(5, "pareja", "es cariñoso, pero le cuesta tanto organizarse que improvisáis todos los planes."),
        new(5, "pareja", "te cocina con ilusión y deja una montaña de platos para que la resuelvas tú."),
        new(6, "pareja", "te apoya cuando lo necesitas, aunque para elegir una película tarda más que la película."),
        new(6, "pareja", "reparte las tareas contigo, pero convierte doblar las sábanas en una pequeña batalla."),
        new(7, "pareja", "sabe escucharte, aunque se emociona tanto cocinando que ensucia todas las cucharas."),
        new(7, "pareja", "se acuerda de tus días importantes y siempre envuelve los regalos con demasiado celo."),
        new(8, "pareja", "nota cuando has tenido un día difícil y prepara tu cena favorita, un poco pasada de sal."),
        new(8, "pareja", "habla contigo para arreglar los desacuerdos y después propone un abrazo larguísimo."),
        new(9, "pareja", "te cuida sin agobiarte y su gran manía es dejarte notas bonitas en sitios inesperados."),
        new(9, "pareja", "celebra tus metas como si fueran suyas y hace demasiadas fotos de cada celebración."),
        new(10, "pareja", "además de quererte, sabe pedir perdón, cumplir acuerdos y alegrarse de que tengas tu espacio."),
        new(10, "pareja", "hace equipo contigo en los días fáciles y en los difíciles, sin llevar una cuenta de favores."),

        new(1, "amigos", "vende tus secretos a cambio de caerle bien a gente que acaba de conocer."),
        new(1, "amigos", "organiza planes para dejarte fuera y luego se burla de que te haya dolido."),
        new(2, "amigos", "te pide dinero, evita devolvértelo y presume delante de ti de sus compras nuevas."),
        new(2, "amigos", "se ríe de tus inseguridades incluso después de que le pidas que pare."),
        new(3, "amigos", "solo se acuerda de que existes cuando necesita mudarse o pedirte un favor."),
        new(3, "amigos", "desaparece cuando necesitas ayuda y vuelve justo cuando toca celebrar."),
        new(4, "amigos", "confirma todos los planes y los cancela a última hora por cualquier oferta mejor."),
        new(4, "amigos", "acapara las conversaciones y nunca llega a preguntarte cómo estás."),
        new(5, "amigos", "es buena compañía, pero te toca organizar absolutamente todas las quedadas."),
        new(5, "amigos", "te escucha de verdad, aunque contesta los mensajes cuando el plan ya ha pasado."),
        new(6, "amigos", "siempre intenta ayudarte, aunque sus consejos empiezan con una historia larguísima sobre sí mismo."),
        new(6, "amigos", "se apunta a tus planes, pero hay que esperarle porque siempre calcula mal el trayecto."),
        new(7, "amigos", "te acompaña a hacer trámites aburridos, aunque convierte el camino en un concierto desafinado."),
        new(7, "amigos", "recuerda lo que te preocupa y manda tantos memes de ánimo que te llena la galería."),
        new(8, "amigos", "te ayuda con la mudanza sin que se lo pidas y etiqueta las cajas con chistes malísimos."),
        new(8, "amigos", "nota si estás callado, te pregunta en privado y aparece con tus snacks favoritos."),
        new(9, "amigos", "defiende tu ausencia con el mismo cariño con el que celebra tu presencia."),
        new(9, "amigos", "está en los momentos importantes y todavía conserva aquella pulsera fea que le regalaste."),
        new(10, "amigos", "puedes contarle lo bueno y lo malo sabiendo que habrá alegría, apoyo y cero juicios."),
        new(10, "amigos", "te dice la verdad con cariño, respeta tus límites y nunca convierte la amistad en una deuda."),

        new(1, "broma", "llama broma a hacerte llorar y todavía exige que te rías."),
        new(1, "broma", "inventa rumores sobre ti para entretener al grupo y luego dice que no era para tanto."),
        new(2, "broma", "publica una caída tuya aunque le hayas pedido que no la suba."),
        new(2, "broma", "su repertorio entero consiste en ridiculizar a quien menos puede defenderse."),
        new(3, "broma", "estropea sorpresas importantes por grabar tu cara de decepción."),
        new(3, "broma", "te esconde cosas que necesitas y alarga la broma aunque ya vayas tarde."),
        new(4, "broma", "interrumpe cualquier conversación seria con efectos de sonido del móvil."),
        new(4, "broma", "repite el mismo chiste hasta que alguien se ríe por puro agotamiento."),
        new(5, "broma", "a veces te hace llorar de risa y otras necesita explicar el chiste durante varios minutos."),
        new(5, "broma", "tiene ocurrencias buenas, pero mete un juego de palabras en cada frase."),
        new(6, "broma", "sabe reírse de sí mismo, aunque remata todos los chistes con su propia carcajada."),
        new(6, "broma", "anima las esperas con imitaciones que solo se parecen si cierras mucho los ojos."),
        new(7, "broma", "te saca una sonrisa en un mal día, aunque su baile de victoria necesita jubilación."),
        new(7, "broma", "hace bromas sin herir a nadie y celebra cada chiste malo como si hubiera ganado un premio."),
        new(8, "broma", "sabe cuándo hacerte reír y cuándo escucharte, aunque guarde una colección absurda de voces."),
        new(8, "broma", "convierte un imprevisto en una anécdota divertida sin quitarle importancia a cómo te sientes."),
        new(9, "broma", "hace reír a todo el grupo sin usar a nadie de blanco y se ríe más fuerte de tus chistes."),
        new(9, "broma", "te devuelve la sonrisa sin presionarte y conserva un meme especial para cada uno de tus días malos."),
        new(10, "broma", "su humor une al grupo, incluye a quien acaba de llegar y sabe parar en cuanto alguien lo necesita."),
        new(10, "broma", "consigue que todos brillen contando una historia y jamás necesita avergonzar a nadie para divertir."),

        new(1, "fiesta", "presiona a los demás para beber aunque hayan dicho claramente que no."),
        new(1, "fiesta", "deja tirado a un amigo que necesita ayuda porque no quiere perderse la siguiente canción."),
        new(2, "fiesta", "rompe algo en casa del anfitrión y acusa a otra persona para no pagarlo."),
        new(2, "fiesta", "invita desconocidos a tu casa sin permiso y se va antes de que puedas decirle nada."),
        new(3, "fiesta", "monta una discusión si el grupo no hace exactamente lo que quiere."),
        new(3, "fiesta", "promete ayudar a recoger, pero se escabulle dejando todo su desastre."),
        new(4, "fiesta", "secuestra la música toda la noche y se salta cualquier canción que no haya elegido."),
        new(4, "fiesta", "llega sin avisar con varios acompañantes y espera que haya comida para todos."),
        new(5, "fiesta", "lleva algo para compartir, pero se queda hablando solo con la gente que ya conoce."),
        new(5, "fiesta", "anima el ambiente al principio y luego pasa la mitad de la noche grabando historias."),
        new(6, "fiesta", "ayuda a preparar todo, aunque alarga su turno de karaoke más de la cuenta."),
        new(6, "fiesta", "se adapta a cualquier plan, pero pregunta cuándo sale la comida cada poco rato."),
        new(7, "fiesta", "presenta a quienes no se conocen, aunque se empeña en enseñarles su baile favorito."),
        new(7, "fiesta", "trae opciones para todos y siempre propone una foto de grupo con poses ridículas."),
        new(8, "fiesta", "se fija en quien está apartado y lo incluye sin ponerlo en el centro de atención."),
        new(8, "fiesta", "ayuda a recoger mientras sigue bailando con la escoba como pareja."),
        new(9, "fiesta", "respeta el ritmo de cada persona y comprueba que todos tengan una vuelta segura a casa."),
        new(9, "fiesta", "consigue que el anfitrión también disfrute porque se ocupa de los pequeños imprevistos."),
        new(10, "fiesta", "hace que todo el mundo se sienta invitado, respeta cada no y deja la casa mejor de como la encontró."),
        new(10, "fiesta", "lleva alegría sin presión, cuida al grupo y se queda hasta el final para echar una mano."),

        new(1, "cotidiano", "trata fatal al personal que le atiende y se enorgullece de hacerlo."),
        new(1, "cotidiano", "se aprovecha de los errores de los demás aunque sepa que alguien saldrá perjudicado."),
        new(2, "cotidiano", "se cuela en todas las filas y luego se burla de quienes protestan."),
        new(2, "cotidiano", "toma cosas prestadas, las estropea y te dice que haberlas cuidado era tu problema."),
        new(3, "cotidiano", "deja las zonas comunes sucias y espera que alguien más se canse primero."),
        new(3, "cotidiano", "hace ruido de madrugada y responde que sus vecinos deberían acostumbrarse."),
        new(4, "cotidiano", "nunca repone lo que termina y deja el envase vacío como si fuera decoración."),
        new(4, "cotidiano", "llega tarde a todo y ni siquiera avisa para que puedas organizarte."),
        new(5, "cotidiano", "comparte lo que tiene, pero encontrar algo entre su desorden es una expedición."),
        new(5, "cotidiano", "cumple lo importante, aunque hay que recordarle siempre los pequeños recados."),
        new(6, "cotidiano", "se ofrece a hacer la compra, pero vuelve con todos los antojos y se olvida del pan."),
        new(6, "cotidiano", "te prepara café por la mañana, aunque su alarma necesite varios intentos para despertarlo."),
        new(7, "cotidiano", "repara lo que se rompe en casa, aunque necesite ver el tutorial a cámara lenta."),
        new(7, "cotidiano", "es atento con todo el mundo y cuenta las historias empezando demasiado atrás."),
        new(8, "cotidiano", "devuelve lo prestado a tiempo, limpio y con una nota de agradecimiento algo cursi."),
        new(8, "cotidiano", "te facilita los días complicados y solo pide elegir la música mientras cocina."),
        new(9, "cotidiano", "hace pequeños favores sin anunciarlos y siempre deja la última galleta para compartir."),
        new(9, "cotidiano", "cumple su palabra hasta en lo pequeño y lleva un paraguas extra por si alguien lo necesita."),
        new(10, "cotidiano", "es igual de amable cuando nadie lo ve y hace más fácil la vida de quienes tiene cerca."),
        new(10, "cotidiano", "cuida los espacios compartidos, agradece la ayuda y ofrece la suya sin esperar aplausos.")
    ];
}
